import type { Channel } from '@/types/recommendation';

export const CHANNELS: Channel[] = [
  {
    name: 'Reddit r/SideProject',
    type: 'community',
    audience: 'general',
    outreachType: 'reddit',
    url: 'https://www.reddit.com/r/SideProject/',
    description: 'Community for sharing and getting feedback on side projects.',
    audienceSize: '200k+ members',
    effort: 'low',
    cost: 'free',
  },
  {
    name: 'Reddit r/startups',
    type: 'community',
    audience: 'general',
    outreachType: 'reddit',
    url: 'https://www.reddit.com/r/startups/',
    description: 'Startup-focused community for founders sharing progress and seeking advice.',
    audienceSize: '1.2M+ members',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'Reddit r/indiehackers',
    type: 'community',
    audience: 'general',
    outreachType: 'reddit',
    url: 'https://www.reddit.com/r/indiehackers/',
    description: 'Subreddit for indie hackers building profitable online businesses.',
    audienceSize: '50k+ members',
    effort: 'low',
    cost: 'free',
  },
  {
    name: 'Reddit r/webdev',
    type: 'community',
    audience: 'developer',
    outreachType: 'reddit',
    url: 'https://www.reddit.com/r/webdev/',
    description: 'Web development community for sharing projects and tools.',
    audienceSize: '2M+ members',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'Hacker News (Show HN)',
    type: 'news',
    audience: 'developer',
    outreachType: 'hackernews',
    url: 'https://news.ycombinator.com/showhn.html',
    description: 'Show HN is for sharing your own work. Tech-savvy audience with high-quality discussion.',
    audienceSize: '10M+ monthly visitors',
    effort: 'high',
    cost: 'free',
  },
  {
    name: 'Product Hunt',
    type: 'directory',
    audience: 'product',
    outreachType: 'producthunt',
    url: 'https://www.producthunt.com/',
    description: 'The go-to platform for launching new products. Strong community of early adopters.',
    audienceSize: '5M+ monthly visitors',
    effort: 'high',
    cost: 'free',
  },
  {
    name: 'Indie Hackers',
    type: 'community',
    audience: 'product',
    outreachType: 'indiehackers',
    url: 'https://www.indiehackers.com/',
    description: 'Community of founders sharing revenue numbers, strategies, and launch stories.',
    audienceSize: '100k+ members',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'Dev.to',
    type: 'community',
    audience: 'developer',
    outreachType: 'devto',
    url: 'https://dev.to/',
    description: 'Developer blogging platform. Great for technical write-ups and Show-style posts.',
    audienceSize: '20M+ monthly visitors',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'Twitter / X',
    type: 'social',
    audience: 'general',
    outreachType: 'twitter',
    url: 'https://twitter.com/',
    description: 'Build in public, share updates, connect with other founders and early adopters.',
    audienceSize: '500M+ users',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'LinkedIn',
    type: 'social',
    audience: 'general',
    outreachType: 'linkedin',
    url: 'https://www.linkedin.com/',
    description: 'Professional network. Effective for B2B tools and professional-audience products.',
    audienceSize: '900M+ users',
    effort: 'medium',
    cost: 'free',
  },
  {
    name: 'BetaList',
    type: 'directory',
    audience: 'product',
    outreachType: 'community',
    url: 'https://betalist.com/',
    description: 'Directory for discovering and getting early access to upcoming startups.',
    audienceSize: '60k+ subscribers',
    effort: 'low',
    cost: 'free',
  },
  {
    name: 'Launching.io',
    type: 'directory',
    audience: 'product',
    outreachType: 'community',
    url: 'https://launching.io/',
    description: 'Curated directory to submit and discover new product launches.',
    audienceSize: '10k+ visitors',
    effort: 'low',
    cost: 'free',
  },
  {
    name: 'Lobste.rs',
    type: 'news',
    audience: 'developer',
    outreachType: 'community',
    url: 'https://lobste.rs/',
    description: 'Invite-only link aggregation for computing-related content. High signal-to-noise.',
    audienceSize: '50k+ members',
    effort: 'high',
    cost: 'free',
  },
  {
    name: 'Hacker Newsletter',
    type: 'email',
    audience: 'developer',
    outreachType: 'email',
    url: 'https://hackernewsletter.com/',
    description: 'Weekly curated newsletter of top Hacker News stories. Pitch your project for inclusion.',
    audienceSize: '60k+ subscribers',
    effort: 'low',
    cost: 'free',
  },
  {
    name: 'Ben\'s Bites',
    type: 'email',
    audience: 'general',
    outreachType: 'email',
    url: 'https://bensbites.com/',
    description: 'AI-focused newsletter. Great for AI/ML-related product launches.',
    audienceSize: '100k+ subscribers',
    effort: 'low',
    cost: 'low',
  },
  {
    name: 'GitHub Trending',
    type: 'community',
    audience: 'developer',
    outreachType: 'community',
    url: 'https://github.com/trending',
    description: 'Open-source projects that gain traction appear on GitHub Trending.',
    audienceSize: '100M+ developers',
    effort: 'high',
    cost: 'free',
  },
  {
    name: 'Uneed',
    type: 'directory',
    audience: 'product',
    outreachType: 'community',
    url: 'https://uneed.best/',
    description: 'Free product directory with daily launches. Quick submission process.',
    audienceSize: '20k+ monthly visitors',
    effort: 'low',
    cost: 'free',
  },
];
